### ISSUE TITLE
Exodus Movie Player

### ISSUE THREAD

**Issue by LJHookem14** [OpenELEQ/verified-metalliq-players#1]
Thanks for adding RDLite back. Now I see Exodus movie player is missing now after latest update. Exodus for TV Shows is available option however. 

I had the RDLite issue and put it on the wrong repo so my apologies on that the other day. Thanks for all that your doing.

**Comment by OpenELEQ** [comment]
Exodus changed structure so no longer viable for direct player without modification to exodus itself which I am not going to do. Workaround works for tvshows sort off but not for movies, use a different player instead.
