### ISSUE TITLE
REQUEST: red beard torrent streaming player

### ISSUE THREAD

**Issue by chiefkes** [OpenELEQ/verified-metalliq-players#10]
Can I put in a request for a player for the new and brilliant red beard addon:

https://forums.tvaddons.ag/dudehere-addons/46786-red-beard-torrent-streaming.html

Cheers

**Comment by OpenELEQ** [comment]
Will give it a go soon but do keep in mind that DudeHere implemented similar block code as Exodus and Salts so a (small) modification to script.module.dudehere.routines will be probably be required to make optimal use of the player.

**Comment by chiefkes** [comment]
OK.  If you'd like I could post on the TVA forums asking for this to be removed.  Someone else posted about metalliq and he seemed receptive to the idea of a metalliq player but 'didn't know much about it', so I'm guessing the block isn't focussed at metalliq in particular

**Comment by chiefkes** [comment]
But fine to make the modification of course

**Comment by chiefkes** [comment]
Posted on TVA

**Comment by OpenELEQ** [comment]
First attempt submitted but something's off, don't have time to look into now. Will continue beginning of february probably.
