### ISSUE TITLE
KODI Popcorn time metalliq player

### ISSUE THREAD

**Issue by Zero0Q** [OpenELEQ/verified-metalliq-players#4]
Hi,
Could you build metalliq player for new KODI Popcorn time  from  this: https://github.com/markop159/KODI-Popcorn-Time
Thanks

**Comment by OpenELEQ** [comment]
Installed that version but couldn't get anything to play at all so can't make a player.

**Comment by Zero0Q** [comment]
It's all good, we tried. Thanks

**Comment by Zero0Q** [comment]
What about this addon: https://github.com/ruuk/script.bluray.com
It would be great to check movies from library about info.
Thanks

**Comment by OpenELEQ** [comment]
Not going to make a **play**er for an addon that doesn't **play**... If you want more info on movies/tvshows, use Extended Info Mod instead, available from my repo.
