### ISSUE TITLE
Quasar needs to be changed so mettaliq respects auto-play.

### ISSUE THREAD

**Issue by Rick7C2** [OpenELEQ/verified-metalliq-players#5]
Currently the way the mettalliq quasar player is It will auto-play regardless of if you have that option enabled in quasar settings.

Please see this commit so you can fix it.

https://github.com/metate/official-meta-players/commit/214f8f0794ecdec77e78bd3052c282a528033e34

Thanks

**Comment by OpenELEQ** [comment]
Fixed, custom quasar players available in custom-player-repo now
